### ISSUE TITLE
DataFrameでの標準化について

### ISSUE THREAD

**Issue by KagenoMoheji** [nkmk/python-snippets#2]
データアナリスト初心者で勉強中の身なので間違いかもしれません．
間違いでしたら指摘お願いします．

https://github.com/nkmk/python-snippets/blob/0c40d0fc73935d4143b8827dd61777cf0ddc6f63/notebook/pandas_normalization.py#L63
上記コードについて，カラムごとに独立した項目でありカラム別に標準化するとして，下記のようにそれぞれの関数に引数`axis`が必要ではないでしょうか？
```
print((df - df.values.mean(axis=0)) / df.values.std(axis=0, ddof=1))
```

**Comment by nkmk** [comment]
`(df - df.values.mean(axis=0)) / df.values.std(axis=0, ddof=1)`でも間違いではないですが、列ごとに処理する場合、`values`を使う必要はありません。

https://github.com/nkmk/python-snippets/blob/0c40d0fc73935d4143b8827dd61777cf0ddc6f63/notebook/pandas_normalization.py#L33-L37

https://github.com/nkmk/python-snippets/blob/0c40d0fc73935d4143b8827dd61777cf0ddc6f63/notebook/pandas_normalization.py#L39-L43

L57およびL63は全体に対して処理する例です。
