### ISSUE TITLE
Potential Error in Usage on Website

### ISSUE THREAD

**Issue by AOrps** [nkmk/python-snippets#5]
https://note.nkmk.me/en/python-platform-system-release-version/ 

![](https://imgur.com/a/HiJOr8B)
- If you can't see the image: 

On the ubuntu section, it shows 
```
print(platform.system())
# Darwin

print(platform.release())
# 18.2.0

print(platform.version())
# Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64

print(platform.platform())
# Darwin-18.2.0-x86_64-i386-64bit
```

Naturally, I wouldn't be too skeptical, maybe Ubuntu was using the Darwin kernel during 18.04. I couldn't check or tell you with 100% certainty but I noticed at the bottom it said `source: platform_usage_mac.py` so with those 2 things, it seemed a a little sus. So I thought I would bring it to your attention that you might have a potential error in your website and you might want to rectify for others. 

Thanks and I really appreciate how you creating this repo of python snippets. Have a good one!

**Comment by nkmk** [comment]
Thanks!
Fixed a mistake on the site.
